FROM node:14.0.0 as build

LABEL author="Mit Chang"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN sudo npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "g", "daemon off;"]


